version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
